services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPWD
      MYSQL_DATABASE: TP4_BDD
      MYSQL_USER: user_es
      MYSQL_PASSWORD: azerty13
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lan_services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - lan_services
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - lan_services
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./mysql-connector-j-8.4.0:/usr/share/logstash/mysql-connector-j-8.4.0
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - mysql
    networks:
      - lan_services
volumes:
  mysql_data:
  es_data:
networks:
  lan_services:
    driver: bridge
